export component Slider inherits Rectangle {
    in property <angle> rotation: 0;

    clip: true;

    Rectangle {
        border-radius: 200px;
        width: 180px;
        height: 180px;
        background: white;
        transform-rotation: rotation;
        Rectangle {
            border-radius: 20px;
            width: 15px;
            height: 15px;
            background: red;
            x: parent.x;
            y: parent.y;
        }
    }
}
